apiVersion: books.com.books.com/v1
kind: Bookstore
metadata:
  labels:
    app.kubernetes.io/name: bookstore
    app.kubernetes.io/managed-by: kustomize
  name: bookstore-sample
spec:
  replicas: 4
  container:
    image: "hamim99/book-server:latest"
    port: 8080

